### ISSUE TITLE
Animation file crashes Android but works on iOS

### ISSUE THREAD

**Issue by mistenkt** [airbnb/lottie-react-native#137] opened 2017-05-30 12:35 UTC
This is the error i get when trying to access the view in android that has the animation
`05-30 14:31:18.358 28244-28275/com.momentiumapp E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
                                                                  Process: com.momentiumapp, PID: 28244
                                                                  java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                      at android.os.AsyncTask$3.done(AsyncTask.java:309)
                                                                      at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                      at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                      at java.lang.Thread.run(Thread.java:818)
                                                                   Caused by: com.facebook.react.bridge.NoSuchKeyException: couldn't find key k in dynamic object
                                                                      at com.facebook.react.bridge.ReadableNativeMap.getType(Native Method)
                                                                      at com.airbnb.android.react.lottie.JSONReadableMap.get(JSONReadableMap.java:93)
                                                                      at com.airbnb.lottie.animatable.AnimatablePathValue.<init>(AnimatablePathValue.java:53)
                                                                      at com.airbnb.lottie.model.Layer.fromJson(Layer.java:110)
                                                                      at com.airbnb.lottie.model.LottieComposition.fromJsonSync(LottieComposition.java:145)
                                                                      at com.airbnb.lottie.model.LottieComposition$JsonCompositionLoader.doInBackground(LottieComposition.java:287)
                                                                      at com.airbnb.lottie.model.LottieComposition$JsonCompositionLoader.doInBackground(LottieComposition.java:275)
                                                                      at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)`

and the animation im trying to run is here: https://gist.github.com/mistenkt/c43b36529a644d4996e1df8131df3d76

It works fine on iOS. So there is something specific to this animation that does not work on android, but i cannot figure out what it is.

**Comment by kiwipxl** [comment] 2017-05-31 13:09
Seems to be happening for me too. Note that the animation works fine in bodymovin, just not lottie react-native on android.

**Comment by kiwipxl** [comment] 2017-06-01 10:58
Apologies for hijacking this issue, but I've found the cause of my problem. Apparently frame rate and "op" can only be parsed as an integer and will crash if it's a number.
`"fr": 29.9700012207031,
  "ip": 0,
  "op": 120.0000048877,`
Using the following values above (or, really any number) will cause the same crash OP is getting (I don't see any other errors on logcat either).

As for OP, using your json file doesn't seem to crash on android for me, but no animation is playing either. Not sure what's going on there.

**Comment by tehfailsafe** [comment] 2017-06-02 20:59
This is happening for me as well. Latest Lottie, RN, and everything freshly installed yesterday. My body movin json export has `"fr":29.9700012207031,"ip":0,"op":101.000004113814,` and the project crashes as soon as it tries to play the animation.

Changing to `"fr":30,"ip":0,"op":101,` and everything works smooth.

**Comment by gpeal** [comment] 2017-08-11 07:02
This should be fixed by #129

**Closed by gpeal** 2017-08-11 07:02 UTC
