### ISSUE TITLE
how to uninstall/remove this package?

### ISSUE THREAD

**Issue by sibelius** [airbnb/lottie-react-native#158] opened 2017-07-24 19:47 UTC
I think it is worth to add a section on README.me of how to remove this package

**Comment by ShariqMush** [comment] 2017-08-09 13:08
I'm having same issue, when I unlink and uninstall the package, it does not let me run the app for android and gives me this error: 
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > Configuration with name 'default' not found.
```

**Comment by lappalj4** [comment] 2017-08-12 13:15
Yes please, I would also like to uninstall this to try and fix my build errors with a fresh install. I am not very familiar with the ios build system so I don't really know all of the steps required for a full uninstall

**Comment by gpeal** [comment] 2017-08-16 21:42
@sibelius @lappalj4 What do you mean by uninstall/remove?

**Comment by lappalj4** [comment] 2017-08-16 22:10
@gpeal I can only speak for myself, but coming from the Android side of things I often find myself stuck in Xcode for hours on end trying to debug a failing build with no idea of what the actual f*** the error logs are trying to tell me... I personally have a hard time figuring out if some of the errors are caused by this library or not, or some misconfiguration I made in Xcode, or even another library that I installed / misconfigured. It would be helpful for the sake of debugging to be able to remove this library completely and retry from a clean slate. 

So a list of what steps to take / files to edit to completely wipe out this library from my code would be super helpful.

**Comment by gpeal** [comment] 2017-08-16 23:09
@lappalj4 iOS builds can be a bit of a pain ;) However, there is nothing special about this library so that would be out of scope for Lottie.

**Closed by gpeal** 2017-08-16 23:09 UTC

**Comment by Luckygirlllll** [comment] 2018-03-23 16:45
I have the same problem, I have deleted Lottie from the project, but now getting this error undefined is not an object (evaluating _reactNative.UIManager.LottieAnimationView.Commands)
<img width="346" alt="screen shot 2018-03-23 at 16 37 05" src="https://user-images.githubusercontent.com/10096433/37842252-e7bed70c-2ec1-11e8-8d02-7d778563bb83.png">

**Comment by MohanadeviK** [comment] 2018-07-07 17:43
+ 1

**Comment by MohanadeviK** [comment] 2018-07-07 17:43
@Luckygirlllll Did you get any solution.
