### ISSUE TITLE
Partial progress loop [question]

### ISSUE THREAD

**Issue by sospedra** [airbnb/lottie-react-native#173] opened 2017-08-17 15:06 UTC
Is possible to just loop a part of the animation?

Imagine you have the typical button which has:

1. Initial value
2. Loading value
3. Done value

![submit_button](https://user-images.githubusercontent.com/3116899/29419077-6db4864a-836e-11e7-95c9-95ec466ffa9a.gif)

The loading is variable to some promise/callback/whatever. Meaning that the duration time is undefined.

Is there any way to keep the `Loading value` running in a loop instead of the whole animation?
I just can think in 3 isolated animations but I'm afraid os possible flickerings.

Thank you

**Comment by sospedra** [comment] 2017-08-26 14:25
Any update on this?

**Comment by gpeal** [comment] 2017-09-23 00:14
Duplicate of #178

**Closed by gpeal** 2017-09-23 00:14 UTC
