### ISSUE TITLE
Build error -------  same name across two different files.

### ISSUE THREAD

**Issue by kaiyes** [airbnb/lottie-react-native#30] opened 2017-02-03 04:06 UTC
Hi, git cloned and then npm installed. Then ran npm start , gives me this error. Opened another tab and ran `sudo gem install cocoapods`, `npm run build:pods` and then `npm run run:ios` which opens a frozen simulator window 
![screen shot 2017-02-03 at 10 00 16](https://cloud.githubusercontent.com/assets/5293742/22579140/eb3564c4-e9f7-11e6-8126-5f9afeef9f2a.png)

**Comment by lelandrichardson** [comment] 2017-02-03 05:59
@kaiyes interesting. I think this is an RN 0.41 bug. It looks like there's some bundle file being created that shouldn't be. If you delete that 2nd file that's listed it should work.  I'll surface to the RN team and see what they say.

**Comment by lelandrichardson** [comment] 2017-02-03 06:01
Also, this is a duplicate of #29, so I'm closing this and will be tracking progress there

**Closed by lelandrichardson** 2017-02-03 06:01 UTC
