### ISSUE TITLE
App closes when it tries to render Animation with assets

### ISSUE THREAD

**Issue by mloisotto** [airbnb/lottie-react-native#164] opened 2017-07-27 21:03 UTC
I've configured the assets folder with the latest version and as PR #105 says. But the app closes and **without showing any kind of error.** 
This is my code: 
```javascript
import React from 'react';
import Animation from 'lottie-react-native';

export default class AnimatedLoading extends React.Component {

  componentDidMount() {
    this.animation.play();
  }


  render() {
    return (
      <Animation
        ref={animation => { this.animation = animation; }}
        style={{height: 200, width: 200 }}
        source={require('./load-loop.json')}
        imageAssetsFolder={'lottie/images'}
      />
    );
  }
}
```
Android Asset folder config: 
![image](https://user-images.githubusercontent.com/15253362/28691763-5961ad04-731e-11e7-9099-79f13710c3ca.png)

JSON file attached.

[load-loop.json.zip](https://github.com/airbnb/lottie-react-native/files/1181239/load-loop.json.zip)

Any kind of help would be appreciated.

Thanks.

**Comment by kelset** [comment] 2017-07-28 13:55
by looking at the json file, it looks like you renamed the file but not the reference inside it:
` "nm": "*loading*",` should be `  "nm": "load-loop",` I think

**Comment by mloisotto** [comment] 2017-07-31 15:10
Hey @kelset ! Thanks for the answer. I'd tried changing its name but it still happens.

**Comment by kelset** [comment] 2017-07-31 15:45
Ok - so, during my last few experimentations what I can surely tell you is that it crashes because something is missing.

My next guess is that you cannot have a font in the .json you give to lottie, or you need to "link it" as you do for other assets: in your .json you have:

```
  "fonts": {
    "list": [
      { "fName": "BryantLG-RegularAlternate", "ascent": 68.2052612304688 }
    ]
  },
```

**Comment by CliveTeow** [comment] 2017-09-30 12:54
I also facing the same issue.

**Comment by gpeal** [comment] 2017-11-24 21:04
Duplicate of #153

**Closed by gpeal** 2017-11-24 21:04 UTC
