### ISSUE TITLE
ratios off from web

### ISSUE THREAD

**Issue by ryanflorence** [airbnb/lottie-react-native#70] opened 2017-02-21 23:21 UTC
Thanks for the lib :)

I downloaded a json file from lottiefiles.com and it's all goofed up:

![image](https://cloud.githubusercontent.com/assets/100200/23189743/4e673f4a-f849-11e6-8a58-c557da14c0b2.png)

I copy/pasted the example code from the README. The animation looks great on the web, is there some prop I need? It reminds me of screwing up the viewbox values in an svg.

Thanks.

**Comment by ryanflorence** [comment] 2017-02-21 23:23
The gears.json is really off:

![image](https://cloud.githubusercontent.com/assets/100200/23189837/be0ca4ac-f849-11e6-873a-d323166c9c31.png)

**Comment by therealsalih** [comment] 2017-02-28 04:36
@ryanflorence I'll download those and take a look to see what the issue is!

**Comment by therealsalih** [comment] 2017-02-28 05:20
@ryanflorence yea these look broken for me too, it's not on your end. As we're not affiliated with Lottiefiles.com i'm not quite sure why those animations are all wonky and it doesn't look like they've actually tested them on Lottie yet. What Bodymovin supports and what Lottie supports are slightly different at the moment. I'll try to get the AE files from those guys and we'll try to track down some of those differences as we go...

**Comment by gpeal** [comment] 2017-03-20 02:58
@ryanflorence Fyi, Gears and many other animations from lottiefiles works on Android now.

**Comment by lelandrichardson** [comment] 2017-03-29 01:10
@ryanflorence I believe this should now be fixed in `lottie-react-native@1.1.1`. Please try it out and let me know if you still have trouble. Closing this issue for now. Thanks!

**Closed by lelandrichardson** 2017-03-29 01:10 UTC
Labels: bug

**Comment by ryanflorence** [comment] 2017-03-29 06:13
Will do, thanks
