### ISSUE TITLE
Animation not showing up. 

### ISSUE THREAD

**Issue by NicolasBonduel** [airbnb/lottie-react-native#120] opened 2017-04-21 13:56 UTC
I build an Animation with After Effect and am trying to render it in my react-native app.

It doesn't crash or anything, but the screen stays black. I also had to manually edit the JSON file to fix this issue: https://github.com/airbnb/lottie-react-native/issues/118
The example animations are working fine, so I don't think it can be an implementation issue. Also, the files are loading properly on the web version.

Here is my configuration for the creation of the bodymovin files:
```
AE: 14.2.0.198
bodymovin: 4.6.7
```

Here is my json file:
https://gist.githubusercontent.com/NicolasBonduel/69c880c7250c31d9fd3d29a6c24c0d59/raw/1c16f1ea5e2fe8fcfcc0c9788ceb0c9049bfab6b/bodymovin

**Comment by oltodo** [comment] 2017-04-24 14:46
Should your animation look like to this?

![avr -24-2017 16-42-54](https://cloud.githubusercontent.com/assets/483842/25342743/33e2b146-290d-11e7-8a9e-f2b837f16188.gif)

**Comment by NicolasBonduel** [comment] 2017-04-24 14:48
Yes, I got it to work following this: https://github.com/airbnb/lottie-react-native/issues/78#issuecomment-286532808

It is rendered properly now.

**Comment by oltodo** [comment] 2017-04-24 14:58
Ok nice!

Weird, I don't have this constraint. I can import my animation from anywhere and play it with the `Animation` component. 

```jsx
import Animation from 'lottie-react-native';
import anim from '../../assets/anims/MyAnim.json';

// ...

render() {
  return <Animation source={anim} />;
}
```

**Comment by NicolasBonduel** [comment] 2017-04-24 15:03
ohhhh, I was importing it with require(), is it in any way different?

```javascript
import Animation from 'lottie-react-native';
const anim = require('../../../assets/animation.json');

// ...

render() {
    return <Animation source={anim} />;
}
```

**Comment by DavidKuennen** [comment] 2017-04-27 10:30
Having the same problem on android.

**Comment by BenPader** [comment] 2017-04-30 17:12
Having the same problem too, i fixed the frame rate in the JSON, but now it is showing a black screen without anything, and without errors

**Comment by BenPader** [comment] 2017-04-30 17:26
Guys ! i found a workaround !
for lottie-react-native, it is possible that the JSON contains "mistakes".
when you export your animation with bodymovin in After Effects, you have to check your json to be sure it always have a "right" number for the framerate and for the "op" section. (not sure of what it is)

For example, if your JSON contains a 29.97 value, you should replace it with "29" or "30".

This work for me

**Comment by gpeal** [comment] 2017-05-08 04:46
That issue is caused by this: https://github.com/airbnb/lottie-react-native/issues/128 and will be fixed soon.

**Closed by gpeal** 2017-05-08 04:46 UTC

**Comment by nicsachin** [comment] 2019-09-06 13:15
is the issue solved
