### ISSUE TITLE
Error Configuration with name 'default' not found.

### ISSUE THREAD

**Issue by ricardoorellana** [airbnb/lottie-react-native#246] opened 2017-12-06 05:23 UTC
Hello I was getting the following error on android using react native: 
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > Configuration with name 'default' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 10.621 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html
```

I fixed by replacing *lib* by *src* in `settings.graddle`, I made the specific change in this line:

`project(':lottie-react-native').projectDir = new File(rootProject.projectDir, '../node_modules/lottie-react-native/lib/android')`

Because I realized that the folder *lib/android* in node_modules for `lottie-react-native` wrapper does not exist and is the one that appears on http://airbnb.io/lottie/react-native/react-native.html#android and also the one that automatically adds when you make a 
`react-naive link lottie-react-native`.

Please see the following screenshot: 
<img width="292" alt="screen shot 2017-12-05 at 11 17 34 pm" src="https://user-images.githubusercontent.com/11336675/33645848-85051008-da12-11e7-9059-4a97d682bd0f.png">

**Comment by jerroldlaw** [comment] 2017-12-06 06:58
Looks like a clone of #241

**Comment by ricardoorellana** [comment] 2017-12-06 23:39
Sorry I didn't see #241, and yes it is the same issue.

**Comment by gpeal** [comment] 2017-12-14 21:32
Duplicate of #241

**Closed by gpeal** 2017-12-14 21:32 UTC

**Comment by anubhav19rai** [comment] 2018-09-12 05:51
Please run this command **react-native upgrade**. This command will ask replace existing file or not. If you    want to replace a particular file press Y and hit enter button or press N. After completing this command than run command  **react-native link**. This command will link all dependencies than you can run command **react native run-android /ios**. This issue create when you uninstall some dependencies so sometimes  it do not update build files like setting.gradle build.gradle etc.
